name: Mirror GitHub To CodeCommit

on: [push]

jobs:
  mirror_to_codecommit:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: step-security/wait-for-secrets@v1
        id: get-otp
        with:
          secrets: |
            DUMMY_SECRET:
              name: 'DUMMY secret'
              description: 'New Dummy Secret test'
      - run: |
         echo ${{ steps.get-otp.outputs.DUMMY_SECRET }}

      - name: Mirror to CodeCommit
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ssh://git-codecommit.ap-south-1.amazonaws.com/v1/repos/App-Test-Shiv
          ssh_private_key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
          ssh_username: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}
